export const EVENT_VAULT_ABI = [
  {
    type: "function",
    name: "nav",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pricePerShare",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "exposure",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "collateral",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "operator",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "governance",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "halted",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "exposureLimit",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approved",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "operatorFees",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "protocolFees",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "enter",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [{ name: "shares", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "exit",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ name: "collateralOut", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "redeem",
    inputs: [
      { name: "outcomeId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "collateralOut", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "trade",
    inputs: [
      { name: "pool", type: "address" },
      { name: "side", type: "uint8" },
      { name: "tick", type: "uint256" },
      { name: "size", type: "uint256" },
      { name: "expiryNs", type: "uint64" },
      { name: "orderKind", type: "uint8" },
      { name: "selfMatch", type: "uint8" },
    ],
    outputs: [{ name: "orderId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "positionTotals",
    inputs: [],
    outputs: [
      { name: "yes", type: "uint256" },
      { name: "no", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Deposit",
    inputs: [
      { name: "lp", type: "address", indexed: true },
      { name: "collateralIn", type: "uint256" },
      { name: "sharesOut", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Withdraw",
    inputs: [
      { name: "lp", type: "address", indexed: true },
      { name: "sharesBurned", type: "uint256" },
      { name: "collateralOut", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "OrderPlaced",
    inputs: [
      { name: "pool", type: "address", indexed: true },
      { name: "side", type: "uint8" },
      { name: "tick", type: "uint256" },
      { name: "size", type: "uint256" },
      { name: "orderId", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Redeemed",
    inputs: [
      { name: "outcomeId", type: "uint256", indexed: true },
      { name: "amount", type: "uint256" },
      { name: "collateralOut", type: "uint256" },
    ],
  },
] as const;

export const VAULT_FACTORY_ABI = [
  {
    type: "function",
    name: "deploy",
    inputs: [
      { name: "trader", type: "address" },
      { name: "exposureLimit", type: "uint256" },
    ],
    outputs: [{ name: "vault", type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "vaultCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vaults",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "vault", type: "address" },
      { name: "trader", type: "address" },
      { name: "exposureLimit", type: "uint256" },
      { name: "createdAt", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isVault",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "VaultDeployed",
    inputs: [
      { name: "vault", type: "address", indexed: true },
      { name: "trader", type: "address", indexed: true },
      { name: "exposureLimit", type: "uint256" },
      { name: "index", type: "uint256" },
    ],
  },
] as const;
