/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TermsRouteImport } from "./routes/terms"
import { Route as StudioRouteImport } from "./routes/studio"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as PortfolioRouteImport } from "./routes/portfolio"
import { Route as LeaderboardRouteImport } from "./routes/leaderboard"
import { Route as HotTopicsRouteImport } from "./routes/hot-topics"
import { Route as EpochsRouteImport } from "./routes/epochs"
import { Route as EarnRouteImport } from "./routes/earn"
import { Route as BecomeATraderRouteImport } from "./routes/become-a-trader"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TradersIndexRouteImport } from "./routes/traders.index"
import { Route as PotsIndexRouteImport } from "./routes/pots.index"
import { Route as BecomeATraderIndexRouteImport } from "./routes/become-a-trader.index"
import { Route as TradersIdRouteImport } from "./routes/traders.$id"
import { Route as PotsIdRouteImport } from "./routes/pots.$id"
import { Route as LiveIdRouteImport } from "./routes/live.$id"
import { Route as BecomeATraderSettingsRouteImport } from "./routes/become-a-trader.settings"

const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: "/studio",
  path: "/studio",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: "/portfolio",
  path: "/portfolio",
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: "/leaderboard",
  path: "/leaderboard",
  getParentRoute: () => rootRouteImport,
} as any)
const HotTopicsRoute = HotTopicsRouteImport.update({
  id: "/hot-topics",
  path: "/hot-topics",
  getParentRoute: () => rootRouteImport,
} as any)
const EpochsRoute = EpochsRouteImport.update({
  id: "/epochs",
  path: "/epochs",
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: "/earn",
  path: "/earn",
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeATraderRoute = BecomeATraderRouteImport.update({
  id: "/become-a-trader",
  path: "/become-a-trader",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TradersIndexRoute = TradersIndexRouteImport.update({
  id: "/traders/",
  path: "/traders/",
  getParentRoute: () => rootRouteImport,
} as any)
const PotsIndexRoute = PotsIndexRouteImport.update({
  id: "/pots/",
  path: "/pots/",
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeATraderIndexRoute = BecomeATraderIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => BecomeATraderRoute,
} as any)
const TradersIdRoute = TradersIdRouteImport.update({
  id: "/traders/$id",
  path: "/traders/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const PotsIdRoute = PotsIdRouteImport.update({
  id: "/pots/$id",
  path: "/pots/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: "/live/$id",
  path: "/live/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeATraderSettingsRoute = BecomeATraderSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => BecomeATraderRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/become-a-trader": typeof BecomeATraderRouteWithChildren
  "/earn": typeof EarnRoute
  "/epochs": typeof EpochsRoute
  "/hot-topics": typeof HotTopicsRoute
  "/leaderboard": typeof LeaderboardRoute
  "/portfolio": typeof PortfolioRoute
  "/privacy": typeof PrivacyRoute
  "/studio": typeof StudioRoute
  "/terms": typeof TermsRoute
  "/become-a-trader/settings": typeof BecomeATraderSettingsRoute
  "/live/$id": typeof LiveIdRoute
  "/pots/$id": typeof PotsIdRoute
  "/traders/$id": typeof TradersIdRoute
  "/become-a-trader/": typeof BecomeATraderIndexRoute
  "/pots/": typeof PotsIndexRoute
  "/traders/": typeof TradersIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/earn": typeof EarnRoute
  "/epochs": typeof EpochsRoute
  "/hot-topics": typeof HotTopicsRoute
  "/leaderboard": typeof LeaderboardRoute
  "/portfolio": typeof PortfolioRoute
  "/privacy": typeof PrivacyRoute
  "/studio": typeof StudioRoute
  "/terms": typeof TermsRoute
  "/become-a-trader/settings": typeof BecomeATraderSettingsRoute
  "/live/$id": typeof LiveIdRoute
  "/pots/$id": typeof PotsIdRoute
  "/traders/$id": typeof TradersIdRoute
  "/become-a-trader": typeof BecomeATraderIndexRoute
  "/pots": typeof PotsIndexRoute
  "/traders": typeof TradersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/become-a-trader": typeof BecomeATraderRouteWithChildren
  "/earn": typeof EarnRoute
  "/epochs": typeof EpochsRoute
  "/hot-topics": typeof HotTopicsRoute
  "/leaderboard": typeof LeaderboardRoute
  "/portfolio": typeof PortfolioRoute
  "/privacy": typeof PrivacyRoute
  "/studio": typeof StudioRoute
  "/terms": typeof TermsRoute
  "/become-a-trader/settings": typeof BecomeATraderSettingsRoute
  "/live/$id": typeof LiveIdRoute
  "/pots/$id": typeof PotsIdRoute
  "/traders/$id": typeof TradersIdRoute
  "/become-a-trader/": typeof BecomeATraderIndexRoute
  "/pots/": typeof PotsIndexRoute
  "/traders/": typeof TradersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/become-a-trader"
    | "/earn"
    | "/epochs"
    | "/hot-topics"
    | "/leaderboard"
    | "/portfolio"
    | "/privacy"
    | "/studio"
    | "/terms"
    | "/become-a-trader/settings"
    | "/live/$id"
    | "/pots/$id"
    | "/traders/$id"
    | "/become-a-trader/"
    | "/pots/"
    | "/traders/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/earn"
    | "/epochs"
    | "/hot-topics"
    | "/leaderboard"
    | "/portfolio"
    | "/privacy"
    | "/studio"
    | "/terms"
    | "/become-a-trader/settings"
    | "/live/$id"
    | "/pots/$id"
    | "/traders/$id"
    | "/become-a-trader"
    | "/pots"
    | "/traders"
  id:
    | "__root__"
    | "/"
    | "/become-a-trader"
    | "/earn"
    | "/epochs"
    | "/hot-topics"
    | "/leaderboard"
    | "/portfolio"
    | "/privacy"
    | "/studio"
    | "/terms"
    | "/become-a-trader/settings"
    | "/live/$id"
    | "/pots/$id"
    | "/traders/$id"
    | "/become-a-trader/"
    | "/pots/"
    | "/traders/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeATraderRoute: typeof BecomeATraderRouteWithChildren
  EarnRoute: typeof EarnRoute
  EpochsRoute: typeof EpochsRoute
  HotTopicsRoute: typeof HotTopicsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  LiveIdRoute: typeof LiveIdRoute
  PotsIdRoute: typeof PotsIdRoute
  TradersIdRoute: typeof TradersIdRoute
  PotsIndexRoute: typeof PotsIndexRoute
  TradersIndexRoute: typeof TradersIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terms": {
      id: "/terms"
      path: "/terms"
      fullPath: "/terms"
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/studio": {
      id: "/studio"
      path: "/studio"
      fullPath: "/studio"
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/portfolio": {
      id: "/portfolio"
      path: "/portfolio"
      fullPath: "/portfolio"
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/leaderboard": {
      id: "/leaderboard"
      path: "/leaderboard"
      fullPath: "/leaderboard"
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/hot-topics": {
      id: "/hot-topics"
      path: "/hot-topics"
      fullPath: "/hot-topics"
      preLoaderRoute: typeof HotTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/epochs": {
      id: "/epochs"
      path: "/epochs"
      fullPath: "/epochs"
      preLoaderRoute: typeof EpochsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/earn": {
      id: "/earn"
      path: "/earn"
      fullPath: "/earn"
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/become-a-trader": {
      id: "/become-a-trader"
      path: "/become-a-trader"
      fullPath: "/become-a-trader"
      preLoaderRoute: typeof BecomeATraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/traders/": {
      id: "/traders/"
      path: "/traders"
      fullPath: "/traders/"
      preLoaderRoute: typeof TradersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pots/": {
      id: "/pots/"
      path: "/pots"
      fullPath: "/pots/"
      preLoaderRoute: typeof PotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/become-a-trader/": {
      id: "/become-a-trader/"
      path: "/"
      fullPath: "/become-a-trader/"
      preLoaderRoute: typeof BecomeATraderIndexRouteImport
      parentRoute: typeof BecomeATraderRoute
    }
    "/traders/$id": {
      id: "/traders/$id"
      path: "/traders/$id"
      fullPath: "/traders/$id"
      preLoaderRoute: typeof TradersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/pots/$id": {
      id: "/pots/$id"
      path: "/pots/$id"
      fullPath: "/pots/$id"
      preLoaderRoute: typeof PotsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/live/$id": {
      id: "/live/$id"
      path: "/live/$id"
      fullPath: "/live/$id"
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/become-a-trader/settings": {
      id: "/become-a-trader/settings"
      path: "/settings"
      fullPath: "/become-a-trader/settings"
      preLoaderRoute: typeof BecomeATraderSettingsRouteImport
      parentRoute: typeof BecomeATraderRoute
    }
  }
}

interface BecomeATraderRouteChildren {
  BecomeATraderSettingsRoute: typeof BecomeATraderSettingsRoute
  BecomeATraderIndexRoute: typeof BecomeATraderIndexRoute
}

const BecomeATraderRouteChildren: BecomeATraderRouteChildren = {
  BecomeATraderSettingsRoute: BecomeATraderSettingsRoute,
  BecomeATraderIndexRoute: BecomeATraderIndexRoute,
}

const BecomeATraderRouteWithChildren = BecomeATraderRoute._addFileChildren(
  BecomeATraderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeATraderRoute: BecomeATraderRouteWithChildren,
  EarnRoute: EarnRoute,
  EpochsRoute: EpochsRoute,
  HotTopicsRoute: HotTopicsRoute,
  LeaderboardRoute: LeaderboardRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  LiveIdRoute: LiveIdRoute,
  PotsIdRoute: PotsIdRoute,
  TradersIdRoute: TradersIdRoute,
  PotsIndexRoute: PotsIndexRoute,
  TradersIndexRoute: TradersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
